version: 2
jobs:
  android:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: npx envinfo
      - run:
          name: build
          command: |
            apt update && apt install fish vim -y
            chmod +x gradlew && ./gradlew assembleDebug
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

workflows:
  version: 2
  build_and_test:
    jobs:
      - android
